runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  MONGO_URI: "mongodb+srv://MyCareAdmin:bd3Y9iQNmzLFG4s4@mycare.fhqcgyk.mongodb.net/mycare?retryWrites=true&w=majority"
  JWT_SECRET: "mycare_secret_key_2024"
  REACT_APP_API_URL: "https://curecollectivewebapp.el.r.appspot.com/api"

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
    secure: always

  - url: /.*
    script: auto
    secure: always

entrypoint: node server/server.js

# Health check configuration
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2 